*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:20:59 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
writing pidfile to /home/dlgao/project/logs/uwsgi.pid
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x123ec70
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x123ec70 pid: 22032 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22032)
spawned uWSGI worker 1 (pid: 22033, cores: 1)
spawned uWSGI worker 2 (pid: 22034, cores: 1)
Thu Jun 16 15:24:58 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 22034)...
Gracefully killing worker 1 (pid: 22033)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (127.0.0.1:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:24:59 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x2184b40
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x2184b40 pid: 22032 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22032)
spawned uWSGI worker 1 (pid: 22072, cores: 1)
spawned uWSGI worker 2 (pid: 22073, cores: 1)
Thu Jun 16 15:25:02 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 22073)...
Gracefully killing worker 1 (pid: 22072)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:25:03 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x1b62780
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1b62780 pid: 22032 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22032)
spawned uWSGI worker 1 (pid: 22085, cores: 1)
spawned uWSGI worker 2 (pid: 22086, cores: 1)
Thu Jun 16 15:25:12 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 22085)...
Gracefully killing worker 2 (pid: 22086)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:25:13 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x1a86780
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1a86780 pid: 22032 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22032)
spawned uWSGI worker 1 (pid: 22091, cores: 1)
spawned uWSGI worker 2 (pid: 22092, cores: 1)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 416, in _delegate
    mod = __import__(mod, None, None, [''])
  File "./app/controllers/nginxmonitor.py", line 13, in <module>
    from app.helpers import bus
  File "./app/helpers/bus.py", line 8, in <module>
    import xmltodict
ImportError: No module named xmltodict

[pid: 22092|app: 0|req: 1/1] 101.226.103.72 () {38 vars in 709 bytes} [Thu Jun 16 15:25:20 2016] GET /functiontest?signature=c8d3d30085824c05c53cac0d5a7be0f996b1a8fc&echostr=9079606066126149221&timestamp=1466061920&nonce=716490191 => generated 51996 bytes in 83 msecs (HTTP/1.0 500) 1 headers in 63 bytes (2 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 416, in _delegate
    mod = __import__(mod, None, None, [''])
  File "./app/controllers/nginxmonitor.py", line 13, in <module>
    from app.helpers import bus
  File "./app/helpers/bus.py", line 8, in <module>
    import xmltodict
ImportError: No module named xmltodict

[pid: 22092|app: 0|req: 2/2] 58.247.206.143 () {38 vars in 709 bytes} [Thu Jun 16 15:27:17 2016] GET /functiontest?signature=f4197ef4ef98d918145595ab5d57d360b3659719&echostr=8857707031740774399&timestamp=1466062037&nonce=381663636 => generated 51996 bytes in 13 msecs (HTTP/1.0 500) 1 headers in 63 bytes (2 switches on core 0)
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:28:06 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
writing pidfile to /home/dlgao/project/logs/uwsgi.pid
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x2703c70
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x2703c70 pid: 22160 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22160)
spawned uWSGI worker 1 (pid: 22161, cores: 1)
spawned uWSGI worker 2 (pid: 22162, cores: 1)
[pid: 22161|app: 0|req: 1/1] 140.207.54.80 () {38 vars in 710 bytes} [Thu Jun 16 15:28:12 2016] GET /functiontest?signature=41db4d142cd85ca4dc139af5b1ad966e3fee30f1&echostr=8941446622620637119&timestamp=1466062092&nonce=1273701182 => generated 19 bytes in 52 msecs (HTTP/1.0 200) 0 headers in 19 bytes (2 switches on core 0)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app/controllers/nginxmonitor.py", line 66, in POST
    busId  = bus.requestRouteId(keyWord)
  File "./app/helpers/bus.py", line 77, in requestRouteId
    resHtml = open(fileGz,"w")
IOError: [Errno 13] Permission denied: 'tmpfile17059ad0-3394-11e6-a03b-525400faad6c.gz'

[pid: 22161|app: 0|req: 2/2] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 15:29:41 2016] POST /functiontest?signature=9bb9dab814eb1b2b99a93a4752d47bd96788d316&timestamp=1466062181&nonce=1825445448&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=21ca1dd6a2177abf35eefea1bd1597a0d3c94bd0 => generated 39674 bytes in 444 msecs (HTTP/1.1 500) 1 headers in 63 bytes (2 switches on core 0)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app/controllers/nginxmonitor.py", line 66, in POST
    busId  = bus.requestRouteId(keyWord)
  File "./app/helpers/bus.py", line 77, in requestRouteId
    resHtml = open(fileGz,"w")
IOError: [Errno 13] Permission denied: 'tmpfile1d28a65a-3394-11e6-a03b-525400faad6c.gz'

[pid: 22161|app: 0|req: 3/3] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 15:29:51 2016] POST /functiontest?signature=1e41c2d4529bf7a4f37e5f799d3ea936ccd2f44b&timestamp=1466062191&nonce=1132284410&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=1d89da658215f782b929257ba55464aa20948ffb => generated 39674 bytes in 129 msecs (HTTP/1.1 500) 1 headers in 63 bytes (2 switches on core 0)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app/controllers/nginxmonitor.py", line 66, in POST
    busId  = bus.requestRouteId(keyWord)
  File "./app/helpers/bus.py", line 77, in requestRouteId
    resHtml = open(fileGz,"w")
IOError: [Errno 13] Permission denied: 'tmpfile23eaa1c8-3394-11e6-86df-525400faad6c.gz'

[pid: 22162|app: 0|req: 1/4] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:30:02 2016] POST /functiontest?signature=901dba150d1fb5db2fcce29e71f0c6df6dd05a45&timestamp=1466062201&nonce=962502042&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=9909accbbece7241f980ff1d59dd7672dfeb7df1 => generated 39669 bytes in 1261 msecs (HTTP/1.1 500) 1 headers in 63 bytes (2 switches on core 0)
Thu Jun 16 15:30:46 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 22161)...
Gracefully killing worker 2 (pid: 22162)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:30:47 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x1887780
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1887780 pid: 22160 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22160)
spawned uWSGI worker 1 (pid: 22244, cores: 1)
spawned uWSGI worker 2 (pid: 22245, cores: 1)
Thu Jun 16 15:30:50 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 22245)...
Gracefully killing worker 1 (pid: 22244)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:30:51 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x849780
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x849780 pid: 22160 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22160)
spawned uWSGI worker 1 (pid: 22248, cores: 1)
spawned uWSGI worker 2 (pid: 22249, cores: 1)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app/controllers/nginxmonitor.py", line 66, in POST
    busId  = bus.requestRouteId(keyWord)
  File "./app/helpers/bus.py", line 77, in requestRouteId
    resHtml = open(fileGz,"w")
IOError: [Errno 13] Permission denied: 'tmpfile46cc5c36-3394-11e6-bf6b-525400faad6c.gz'

[pid: 22249|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 15:31:00 2016] POST /functiontest?signature=79cf00ca3f22d833e67d61513d2b98374e71dd14&timestamp=1466062260&nonce=2022597570&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=df6f1a792547e6c581103ec4e49834d83a57177b => generated 39657 bytes in 983 msecs (HTTP/1.1 500) 1 headers in 63 bytes (2 switches on core 0)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app/controllers/nginxmonitor.py", line 66, in POST
    busId  = bus.requestRouteId(keyWord)
  File "./app/helpers/bus.py", line 77, in requestRouteId
    resHtml = open(fileGz,"w")
IOError: [Errno 13] Permission denied: 'tmpfile4ced5eda-3394-11e6-bf6b-525400faad6c.gz'

[pid: 22249|app: 0|req: 2/2] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:31:11 2016] POST /functiontest?signature=e66f35a369d5a536bb6245bcaf8cd61f6645d6d6&timestamp=1466062271&nonce=959431094&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=951ed62839f6ffcbcc8c5fb9aade6a537fa1a72d => generated 39652 bytes in 136 msecs (HTTP/1.1 500) 1 headers in 63 bytes (2 switches on core 0)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app/controllers/nginxmonitor.py", line 66, in POST
    busId  = bus.requestRouteId(keyWord)
  File "./app/helpers/bus.py", line 77, in requestRouteId
    resHtml = open(fileGz,"w")
IOError: [Errno 13] Permission denied: 'tmpfile53102f9a-3394-11e6-ba8c-525400faad6c.gz'

[pid: 22248|app: 0|req: 1/3] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:31:22 2016] POST /functiontest?signature=0ae86a462774be10789b1e614bda179bb4a027eb&timestamp=1466062282&nonce=748655274&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=a5d2ac725f4b66f33ba7012564dd96feb3d2c5ce => generated 39652 bytes in 234 msecs (HTTP/1.1 500) 1 headers in 63 bytes (2 switches on core 0)
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:33:55 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
writing pidfile to /home/dlgao/project/logs/uwsgi.pid
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x21f0c60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x21f0c60 pid: 22288 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22288)
spawned uWSGI worker 1 (pid: 22289, cores: 1)
spawned uWSGI worker 2 (pid: 22290, cores: 1)
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:34:26 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
writing pidfile to /home/dlgao/project/logs/uwsgi.pid
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x1ed24f0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1ed24f0 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 22318, cores: 1)
spawned uWSGI worker 2 (pid: 22319, cores: 1)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1753': u'\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3', u'2049': u'\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821'}
################nginxmonitor################## {"1753": "\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3", "2049": "\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821"}
[pid: 22319|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:34:43 2016] POST /functiontest?signature=85b6f66fbc3007dd9980b83bd3100e351c876d24&timestamp=1466062483&nonce=585286336&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=c49ff5c26faa06b78e77c9bdbbed72852263192c => generated 412 bytes in 544 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['1753'] s 1753
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
[pid: 22319|app: 0|req: 2/2] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:34:55 2016] POST /functiontest?signature=955707ea8002fe4ec9ffad44544efd32304b31d9&timestamp=1466062495&nonce=941929163&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=3d0513d03020f1fec3d041a420e5d47cdd8acc97 => generated 1165 bytes in 184 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['1753', '36'] r 1753 36
bus_num=9999device_id=f8:a4:5f:11:21:79index=36route_id=1753show_all=1timestamp=2016-03-31 15:39:08client_credentialsf8:a4:5f:11:21:79
[pid: 22319|app: 0|req: 3/3] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:35:00 2016] POST /functiontest?signature=1050c15a99b128dc66f850b7e723c57e9bc4b3a1&timestamp=1466062500&nonce=777779003&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=f95131d7e11cefcf852fef5644f801df090a4ba7 => generated 912 bytes in 4335 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['592'] 592
device_id=f8:a4:5f:11:21:79is_exact=0keywords=592timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '592'), ('timestamp', '2016-03-31 15:39:00')]) 5cdaffd38ae86fa639063302fe475477
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1429timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1429timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1429': u'\u65b0\u90fd\u4e1c\u7ad9 \u81f3 \u4e1c\u5317\u65fa\u4e2d\u8def', u'1871': u'\u4e1c\u5317\u65fa\u4e2d\u8def \u81f3 \u65b0\u90fd\u4e1c\u7ad9'}
################nginxmonitor################## {"1429": "\u65b0\u90fd\u4e1c\u7ad9 \u81f3 \u4e1c\u5317\u65fa\u4e2d\u8def", "1871": "\u4e1c\u5317\u65fa\u4e2d\u8def \u81f3 \u65b0\u90fd\u4e1c\u7ad9"}
[pid: 22319|app: 0|req: 4/4] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 15:42:49 2016] POST /functiontest?signature=6ebf9e294f880ca512e23934dbb09be74d991468&timestamp=1466062969&nonce=1600773587&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=bc43fdb5e743e177038fa43de38a723b0f9479a4 => generated 412 bytes in 496 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['1429'] s 1429
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1429timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
[pid: 22319|app: 0|req: 5/5] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:43:05 2016] POST /functiontest?signature=c91e4ba0cc2713b33094ff5cbbe4065eb2a392d6&timestamp=1466062985&nonce=340289712&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=271e9d7fccdfaaf09db89d681c48a11086578f4a => generated 588 bytes in 157 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['1429', '6'] r 1429 6
bus_num=9999device_id=f8:a4:5f:11:21:79index=6route_id=1429show_all=1timestamp=2016-03-31 15:39:08client_credentialsf8:a4:5f:11:21:79
[pid: 22319|app: 0|req: 6/6] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:43:15 2016] POST /functiontest?signature=dbf2341936addde68340840e1407ba0a67c0c260&timestamp=1466062995&nonce=827457566&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=dfc1215e98b42376f97bf5e2fdee47b02dea9e42 => generated 341 bytes in 4329 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['379'] 379
device_id=f8:a4:5f:11:21:79is_exact=0keywords=379timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '379'), ('timestamp', '2016-03-31 15:39:00')]) 720e3a7cd5069ec750aa630fe0cb5539
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=593timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=593timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'593': u'\u80b2\u65b0\u5c0f\u533a \u81f3 \u5de6\u5bb6\u5e84', u'594': u'\u5de6\u5bb6\u5e84 \u81f3 \u80b2\u65b0\u5c0f\u533a'}
################nginxmonitor################## {"593": "\u80b2\u65b0\u5c0f\u533a \u81f3 \u5de6\u5bb6\u5e84", "594": "\u5de6\u5bb6\u5e84 \u81f3 \u80b2\u65b0\u5c0f\u533a"}
[pid: 22319|app: 0|req: 7/7] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 15:46:19 2016] POST /functiontest?signature=5e54048acf158b7cd11a50def6c448781f6a2f8b&timestamp=1466063179&nonce=1103529134&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=da18ef59aac9df89dc3a443edf672575a069788f => generated 398 bytes in 461 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['594'] s 594
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=594timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
[pid: 22319|app: 0|req: 8/8] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:46:29 2016] POST /functiontest?signature=8dae0809e081dc281ab178d004ab1380705ad9a2&timestamp=1466063189&nonce=957343875&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=56f36fb3868d3b88498b39580a9ee300979d8a6b => generated 771 bytes in 153 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['594', '17'] r 594 17
bus_num=9999device_id=f8:a4:5f:11:21:79index=17route_id=594show_all=1timestamp=2016-03-31 15:39:08client_credentialsf8:a4:5f:11:21:79
[pid: 22319|app: 0|req: 9/9] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 15:46:37 2016] POST /functiontest?signature=c58ae51389e44aa7ee12f14762d2d7d39de415e1&timestamp=1466063197&nonce=1630095325&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=6dce8cdf117cb4e37fef582ebeaf2730c06b4b6b => generated 615 bytes in 4327 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1753': u'\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3', u'2049': u'\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821'}
################nginxmonitor################## {"1753": "\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3", "2049": "\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821"}
[pid: 22318|app: 0|req: 1/10] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 16:05:07 2016] POST /functiontest?signature=9b292055d6119c05cb3635dea3342d5fbc3975a6&timestamp=1466064307&nonce=1390871616&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=7de159f08b729f917425dd6e02447544ad52dcee => generated 412 bytes in 2258 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
Thu Jun 16 16:45:15 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 22318)...
Gracefully killing worker 2 (pid: 22319)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 16:45:16 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x8c4030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x8c4030 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 23233, cores: 1)
spawned uWSGI worker 2 (pid: 23234, cores: 1)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1753': u'\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3', u'2049': u'\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821'}
################nginxmonitor################## {"1753": "\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3", "2049": "\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821"}
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 23233|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 16:45:25 2016] POST /functiontest?signature=1149cdf14967a6f31602d57fc28f71f7f3860f35&timestamp=1466066725&nonce=236936687&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=69bf43dbb6450ab8682b0b823c112b3b2ae555cd => generated 412 bytes in 1862 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
Thu Jun 16 17:07:31 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 23233)...
Gracefully killing worker 2 (pid: 23234)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 17:07:32 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x1522030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1522030 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 23504, cores: 1)
spawned uWSGI worker 2 (pid: 23505, cores: 1)
[] xxx
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 23504|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 17:07:40 2016] POST /functiontest?signature=bc00c8e1a130992dfbfceecce5da0af6c94f377d&timestamp=1466068060&nonce=391834273&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=a6c0edf415dcd48b429c18115756c27bc55d266d => generated 336 bytes in 65 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
